version: "3"

services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: nomoresecret
      DB_VENDOR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: "nomoresecret"
      DB_ADDR: "keycloak-database"
      DB_PORT: "3306"
      JAVA_OPTS: "-server -Xms128m -Xmx1024m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true"
    ports:
      - "8080:8080"  # host:container
      - "8443:8443"

  keycloak-database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: nomoresecret
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: nomoresecret
